// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/San-Kun/MiniProject/domain"

	mock "github.com/stretchr/testify/mock"
)

// BankAccountRepository is an autogenerated mock type for the BankAccountRepository type
type BankAccountRepository struct {
	mock.Mock
}

// CheckLogin provides a mock function with given fields: BankAccount
func (_m *BankAccountRepository) CheckLogin(bankAccount *domain.BankAccount) (*domain.BankAccount, bool, error) {
	ret := _m.Called(bankAccount)

	var r0 *domain.BankAccount
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) *domain.BankAccount); ok {
		r0 = rf(bankAccount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*domain.BankAccount) bool); ok {
		r1 = rf(bankAccount)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*domain.BankAccount) error); ok {
		r2 = rf(bankAccount)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}


// Create provides a mock function with given fields: BankAccount
func (_m *BankAccountRepository) Create(bankAccount *domain.BankAccount) (*domain.BankAccount, error) {
	ret := _m.Called(bankAccount)

	var r0 *domain.BankAccount
	if rf, ok := ret.Get(0).(func(*domain.BankAccount) *domain.BankAccount); ok {
		r0 = rf(bankAccount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.BankAccount) error); ok {
		r1 = rf(bankAccount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields:
func (_m *BankAccountRepository) ReadAll() (*domain.BankAccounts, error) {
	ret := _m.Called()

	var r0 *domain.BankAccounts
	if rf, ok := ret.Get(0).(func() *domain.BankAccounts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccounts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadByID provides a mock function with given fields: id
func (_m *BankAccountRepository) ReadByID(id int) (*domain.BankAccount, error) {
	ret := _m.Called(id)

	var r0 *domain.BankAccount
	if rf, ok := ret.Get(0).(func(int) *domain.BankAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: id
func (_m *BankAccountRepository) Delete(id int) (*domain.BankAccount, error) {
	ret := _m.Called(id)

	var r0 *domain.BankAccount
	if rf, ok := ret.Get(0).(func(int) *domain.BankAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id
func (_m *BankAccountRepository) Updates(id int) (*domain.BankAccount, error) {
	ret := _m.Called(id)

	var r0 *domain.BankAccount
	if rf, ok := ret.Get(0).(func(int) *domain.BankAccount); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BankAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}