// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/San-Kun/MiniProject/domain"

	mock "github.com/stretchr/testify/mock"
)

// EventTicketRepository is an autogenerated mock type for the EventTicketRepository type
type EventTicketRepository struct {
	mock.Mock
}

// CheckLogin provides a mock function with given fields: EventTicket
func (_m *EventTicketRepository) CheckLogin(eventTicket *domain.EventTicket) (*domain.EventTicket, bool, error) {
	ret := _m.Called(eventTicket)

	var r0 *domain.EventTicket
	if rf, ok := ret.Get(0).(func(*domain.EventTicket) *domain.EventTicket); ok {
		r0 = rf(eventTicket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventTicket)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*domain.EventTicket) bool); ok {
		r1 = rf(eventTicket)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*domain.EventTicket) error); ok {
		r2 = rf(eventTicket)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}


// Create provides a mock function with given fields: EventTicket
func (_m *EventTicketRepository) Create(eventTicket *domain.EventTicket) (*domain.EventTicket, error) {
	ret := _m.Called(eventTicket)

	var r0 *domain.EventTicket
	if rf, ok := ret.Get(0).(func(*domain.EventTicket) *domain.EventTicket); ok {
		r0 = rf(eventTicket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventTicket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.EventTicket) error); ok {
		r1 = rf(eventTicket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields:
func (_m *EventTicketRepository) ReadAll() (*domain.EventTickets, error) {
	ret := _m.Called()

	var r0 *domain.EventTickets
	if rf, ok := ret.Get(0).(func() *domain.EventTickets); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventTickets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadByID provides a mock function with given fields: id
func (_m *EventTicketRepository) ReadByID(id int) (*domain.EventTicket, error) {
	ret := _m.Called(id)

	var r0 *domain.EventTicket
	if rf, ok := ret.Get(0).(func(int) *domain.EventTicket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventTicket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: id
func (_m *EventTicketRepository) Delete(id int) (*domain.EventTicket, error) {
	ret := _m.Called(id)

	var r0 *domain.EventTicket
	if rf, ok := ret.Get(0).(func(int) *domain.EventTicket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventTicket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id
func (_m *EventTicketRepository) Updates(id int) (*domain.EventTicket, error) {
	ret := _m.Called(id)

	var r0 *domain.EventTicket
	if rf, ok := ret.Get(0).(func(int) *domain.EventTicket); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventTicket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}