// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/San-Kun/MiniProject/domain"
	request "github.com/San-Kun/MiniProject/domain/web/request"

	mock "github.com/stretchr/testify/mock"

	response "github.com/San-Kun/MiniProject/domain/web/response"
)

// PaymentTypeUsecase is an autogenerated mock type for the PaymentTypeUsecase type
type PaymentTypeUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *PaymentTypeUsecase) Create(_a0 request.PaymentTypeCreateRequest) (*domain.PaymentType, error) {
	ret := _m.Called(_a0)

	var r0 *domain.PaymentType
	if rf, ok := ret.Get(0).(func(request.PaymentTypeCreateRequest) *domain.PaymentType); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(request.PaymentTypeCreateRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: _a0
func (_m *PaymentTypeUsecase) Login(_a0 request.LoginRequest) (*response.SuccessLogin, error) {
	ret := _m.Called(_a0)

	var r0 *response.SuccessLogin
	if rf, ok := ret.Get(0).(func(request.LoginRequest) *response.SuccessLogin); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SuccessLogin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(request.LoginRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields:
func (_m *PaymentTypeUsecase) ReadAll() (*domain.PaymentTypes, error) {
	ret := _m.Called()

	var r0 *domain.PaymentTypes
	if rf, ok := ret.Get(0).(func() *domain.PaymentTypes); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTypes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadByID provides a mock function with given fields: id
func (_m *PaymentTypeUsecase) ReadByID(id int) (*domain.PaymentType, error) {
	ret := _m.Called(id)

	var r0 *domain.PaymentType
	if rf, ok := ret.Get(0).(func(int) *domain.PaymentType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: id
func (_m *PaymentTypeUsecase) Delete(id int) (*domain.PaymentType, error) {
	ret := _m.Called(id)

	var r0 *domain.PaymentType
	if rf, ok := ret.Get(0).(func(int) *domain.PaymentType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id
func (_m *PaymentTypeUsecase) Updates(id int) (*domain.PaymentType, error) {
	ret := _m.Called(id)

	var r0 *domain.PaymentType
	if rf, ok := ret.Get(0).(func(int) *domain.PaymentType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}