// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/San-Kun/MiniProject/domain"

	mock "github.com/stretchr/testify/mock"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// CheckLogin provides a mock function with given fields: Payment
func (_m *PaymentRepository) CheckLogin(payment *domain.Payment) (*domain.Payment, bool, error) {
	ret := _m.Called(payment)

	var r0 *domain.Payment
	if rf, ok := ret.Get(0).(func(*domain.Payment) *domain.Payment); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(*domain.Payment) bool); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*domain.Payment) error); ok {
		r2 = rf(payment)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}


// Create provides a mock function with given fields: Payment
func (_m *PaymentRepository) Create(payment *domain.Payment) (*domain.Payment, error) {
	ret := _m.Called(payment)

	var r0 *domain.Payment
	if rf, ok := ret.Get(0).(func(*domain.Payment) *domain.Payment); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Payment) error); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields:
func (_m *PaymentRepository) ReadAll() (*domain.Payments, error) {
	ret := _m.Called()

	var r0 *domain.Payments
	if rf, ok := ret.Get(0).(func() *domain.Payments); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payments)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadByID provides a mock function with given fields: id
func (_m *PaymentRepository) ReadByID(id int) (*domain.Payment, error) {
	ret := _m.Called(id)

	var r0 *domain.Payment
	if rf, ok := ret.Get(0).(func(int) *domain.Payment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: id
func (_m *PaymentRepository) Delete(id int) (*domain.Payment, error) { 
	ret := _m.Called(id)

	var r0 *domain.Payment
	if rf, ok := ret.Get(0).(func(int) *domain.Payment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id
func (_m *PaymentRepository) Updates(id int) (*domain.Payment, error) {
	ret := _m.Called(id)

	var r0 *domain.Payment
	if rf, ok := ret.Get(0).(func(int) *domain.Payment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}